repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements.txt

-   repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.12'
    hooks:
    -   id: checkov
        args: [--soft-fail]

-   repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.14.0
    hooks:
    -   id: trivyfs-docker
        args:
          - --skip-dirs
          - ./tests
          - . # last arg indicates the path/file to scan
    -   id: trivyconfig-docker
        args:
          - --skip-dirs
          - ./tests
          - . # last arg indicates the path/file to scan

-   repo: local
    hooks:
    -   id: pa11y
        name: pa11y accessibility check
        entry: pa11y --reporter cli
        language: node
        types: [html]
        additional_dependencies: ['pa11y@6.2.3']