[tools]
hugo-extended = "latest"
node = "latest"
pre-commit = "latest"
python = "latest"
trivy = "latest"
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist

[settings]
python.uv_venv_auto = true